import re

def handler(event, context):
    """Redirect all traffic to the index.html
    Cloudfront and S3 dont seem to have a great way to default all traffic to a specifc
    file in S3. So this lambda function will automatically change
    the request to be for index.html
    This will check if the route ends in a file extension and if it does will try to serve
    it as is. If it does not end in a file extension, it is safe to assume this is a route
    request that should always serve index.html
    This lambda function must therefore be an Origin Request
    It was generated by trying to follow:
    https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html
    """
    request = event['Records'][0]['cf']['request']
    regex = re.compile('\.([\w]){1,}$')
    if not regex.search(request['uri']):
        request['uri'] = '/index.html'
    return request
